####################################################################################
#Author: Sandesh Patil
#Priority: Specified env config will be picked up, otherwise will use default value
#Format: Support both absolute path and relative path.

####################################################################################


default:
  homepage_url: http://automationpractice.com/index.php


test:
  homepage_url: http://automationpractice.com/index.php


staging:
  homepage_url: http://automationpractice.com/index.php


integration:
  homepage_url: http://automationpractice.com/index.php


production:
  homepage_url: http://automationpractice.com/index.php
